name: Lint GitHub Actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run actionlint
        uses: docker://rhysd/actionlint:1.7.11
        with:
          args: -color
